patchedDependencies:
  '@astrojs/starlight': patches/@astrojs__starlight.patch

onlyBuiltDependencies:
  - workerd
  - esbuild
  - sharp

packages:
  - "."

allowBuilds:
  esbuild: true
  sharp: true
  workerd: true
